---
title: "ChIP-seq TF tool result - Parameter comparison"
author: "Leonor Schubert Santana"
date: "`r Sys.Date()`" 
site: workflowr::wflow_site
output:
   workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=F, message=F)
```

```{r data_preparation}
# Load libraries
library(tidyverse)
library(cowplot)
library(ggsci)

# Load utils.functions file
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/utils_functions.R")
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/read_functions.R")

# Define output path
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/chipseq_parameters'
chip.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/data/chipseq/'
fig.path <- "/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/paperPlots_revisions/"

# Find benchmark.rds 
benchmark.rds <- list.files(out.path, recursive = T, pattern = 'benchmark', full.names = T)
tools <- basename(benchmark.rds) %>% gsub('_.*', '', .) %>% unique()

# Define output path
overview.df <- read_rds('~/projects/tf_tool_benchmark/output/benchmark_data/chipseq/overview.RDS')
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/chipseq_parameters/'
rds.files <- list.files(out.path, full.names = T, recursive = T, pattern = 'RDS')
rds.files <- rds.files[grep(rds.files, pattern = 'benchmark.RDS')]

# Rank dict
rank.dict <- c('stringent' = 'rankStr', 'relaxed' = 'rankUnstr')
plot.list <- list()
hitter.results <- list()

for(rn in names(rank.dict)) {
  for(tool.ofi in tools) {
    # Read hitter data.frame
    hitter.df <- read_rds(rds.files[grep(rds.files, pattern = tool.ofi)])  
    # Reformat tool of interst
    tool.ofi <- ifelse(tool.ofi == 'lola', 'LOLA', tool.ofi)
    # Tidy and combine hitter df list
    hitter.df <- lapply(names(hitter.df), function(var.name) {
      hitter.df[[var.name]] %>%
        as_tibble() %>%
        dplyr::rename('rankStr' = 'rank') %>%
        dplyr::rename('rank' = as.character(rank.dict[[rn]])) %>%
        mutate(tool = tool.ofi, var = var.name, rank = (rank*possible_ranks+1)) %>%
        group_by(tool, var) %>%
        mutate(rank_cat = case_when(rank <= 5 ~ '5',
                                    rank > 5 & rank <= 10 ~ '10',
                                    rank > 10 & rank <= 30 ~ '30',
                                    rank > 30 ~ 'Labels recovered',
                                    is.na(rank) ~ 'Processed datasets')) %>%
        group_by(tool, var, rank_cat) %>%
        summarise(n = n()) 
    }) %>% bind_rows
    
    # Reform for tools
    if(tool.ofi == 'CRCmapper') {
      hitter.df <- hitter.df %>% 
        mutate(var = gsub('elgenth', 'elength=', var),
               var = gsub('nmotif', 'nmotif=', var),
               var = gsub('_', ' ', var))
    } else if(tool.ofi == 'homer') {
      hitter.df <- hitter.df %>% 
        mutate(tool = gsub('_', ' + ', gsub('_nlen.*', '', var)),
               var = gsub('.*nlen', 'nlen=', var),
               var = gsub('_', ' ', var)) 
    } else if(tool.ofi == 'LOLA') {
      hitter.df <- hitter.df %>% 
        mutate(var = gsub('minov', 'minov=', var),
               var = gsub('redefineset', 'redefineset=', var),
               var = sub('_', ' ', var)) 
    }else if(tool.ofi == 'MEIRLOP') {
      hitter.df <- hitter.df %>% 
        mutate(var = gsub('kmer', 'kmer=', var),
               var = gsub('1$', '', var),
               var = sub('_', ' ', var),
               var = sub('_', ' ', var))
    } else if(tool.ofi == 'monaLisa') {
      hitter.df <- hitter.df %>% 
        mutate(var = gsub('weakness', 'weakness=', var),
               var = gsub('0_', '0.', var),
               var = gsub('pfer', 'pfer=', var),
               var = gsub('_', ' ', var))
    } else if(tool.ofi == 'RcisTarget') {
      hitter.df <- hitter.df %>%
        mutate(tool = ifelse(grepl(var, pattern = 'with_background'), sprintf('%s + bg', tool), tool),
               var = gsub('.*ground_', '', var),
               var = gsub('_', '.', gsub('rank', 'rank=', var)))
    } else if(tool.ofi == 'TFEA') {
      hitter.df <- hitter.df %>%
         mutate(var = gsub('sw', 'sw=', var),
               var = gsub('lw', 'lw=', var),
               var = gsub('_', ' ', var))
    }
    
    # PLOT: Top X barplot
    for(tofi in unique(hitter.df$tool)) {
      gg.topHittesBar <- hitter.df %>% 
        filter(tool == tofi) %>%
        #summarise(n = 84 - sum(n)) %>%
        #mutate(rank_cat = 'NA') %>%
        #dplyr::select(tool, var, rank_cat, n) %>%
        #bind_rows(., hitter.df) %>%
        mutate(rank_cat = factor(rank_cat, levels = rev(c( '5', '10', '30', 
                                                       'Labels recovered',
                                                       'Processed datasets', 'NA')))) %>%
        filter(rank_cat %in% c('5', '10', '30')) %>%
        group_by(tool, var) %>%
        mutate(n_total = sum(n)) %>%
        ungroup %>%
        mutate(var = factor(var, levels = unique(var[order(n_total)]))) %>%
        ggplot(aes(x = var, y =  n, fill = rank_cat)) + facet_wrap(~tool) +
        geom_bar(stat="identity", color="black") + theme_cowplot(font_size = 5) + 
        coord_flip() + ylim(0, 45) +
        #scale_x_discrete(labels=c("0.005"=expression(bold("0.005")), '1' = expression(bold('1')), parse=TRUE)) +
        xlab('') + ylab("Count") + labs(fill=sprintf("Threshold\n(%s)", rn)) +
        scale_fill_manual(values = c(pal_igv("default")("51")[1:4], "gray46", "white"),
                          breaks=c('Labels recovered', '30', '10', '5', 
                                   'Processed datasets', 'NA')) +
        theme(legend.position = 'none')
        #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 
      print(gg.topHittesBar)  
      plot.list[[rn]][[tofi]] <- gg.topHittesBar
      print(gg.topHittesBar)  
      cat('\n\n')
      
      # Tidy hitter data.frame 
      hitter.results[[rn]][[tofi]]  <- hitter.df %>% 
        filter(tool == tofi) %>%
        mutate(rank_cat = factor(rank_cat, levels = rev(c( '5', '10', '30', 
                                                       'Labels recovered',
                                                       'Processed datasets', 'NA')))) %>%
        filter(rank_cat %in% c('5', '10', '30')) %>%
        group_by(tool, var) %>%
        mutate(n_total = sum(n), rank_type = rn) 
      
      
    }
  }
}

# Print plot
paper <- lapply(plot.list, function(pl) {#
  plot_grid(plotlist = pl, align = 'hv') #
})
paper <- plot_grid(plotlist = paper, align = "hv", labels = c("A", "B"), 
                   axis = "tblr", nrow = 2)
# Save plot
ggsave(paste0(fig.path, "Supp_fig_X_AB.pdf"),
       paper, device = "pdf", width = 18, height = 22, units = "cm")
```

```{r default_comparison} 
# Define output path
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/chipseq'

# Find benchmark.rds 
benchmark.rds <- list.files(out.path, recursive = T, pattern = 'benchmark', full.names = T)
default.results <- lapply(tools, function(tool.ofi) {
  print(tool.ofi)
   # Read hitter data.frame
   hitter.df <- read_rds(benchmark.rds[grep(benchmark.rds, pattern = tool.ofi)])  
   if(is_tibble(hitter.df)) hitter.df <- list(tool.ofi = hitter.df)
   # Reformat tool of interst
   tool.ofi <- ifelse(tool.ofi == 'lola', 'LOLA', tool.ofi)
   # Tidy and combine hitter df list
   hitter.df <- lapply(names(rank.dict), function(rn) {
    lapply(names(hitter.df), function(var.name) {
      hitter.df[[var.name]] %>%
        as_tibble() %>%
        dplyr::rename('rankStr' = 'rank') %>%
        dplyr::rename('rank' = as.character(rank.dict[[rn]])) %>%
        mutate(tool = tool.ofi, var = var.name, rank = (rank*possible_ranks+1)) %>%
        group_by(tool, var) %>%
        mutate(rank_cat = case_when(rank <= 5 ~ '5',
                                        rank > 5 & rank <= 10 ~ '10',
                                        rank > 10 & rank <= 30 ~ '30',
                                        rank > 30 ~ 'Labels recovered',
                                        is.na(rank) ~ 'Processed datasets')) %>%
        group_by(tool, var, rank_cat) %>%
        summarise(n = n())  %>%
        mutate(rank_cat = factor(rank_cat, levels = rev(c( '5', '10', '30', 
                                                       'Labels recovered',
                                                       'Processed datasets', 'NA')))) %>%
        filter(rank_cat %in% c('5', '10', '30')) %>%
        group_by(tool, var) %>%
        mutate(n_total = sum(n[rank_cat %in% c('5', '10', '30')]),
               rank_type = rn) 
    }) %>% bind_rows
   }) %>% bind_rows
   
   if(tool.ofi == 'homer') {
     hitter.df <- hitter.df %>% 
       mutate(tool = str_to_upper(tool), 
              tool = case_when(grepl(var, pattern = 'using back.*peaks$') ~ sprintf('%s + bg', tool),
                               grepl(var, pattern = 'using back.*motifs$') ~ sprintf('%s + Lambert + bg', tool),
                               grepl(var, pattern = 'using no back.*peaks$') ~ sprintf('%s', tool),
                               grepl(var, pattern = 'using no back.*motifs$') ~ sprintf('%s + Lambert', tool)))
   } else if(tool.ofi == 'RcisTarget') {
     hitter.df <- hitter.df %>% 
       mutate(tool = ifelse(grepl(var, pattern = 'without'),  tool, sprintf('%s + bg', tool)))
   }
   
  
   return(hitter.df)
})

# PLOT: Recovery barplots
gg.recovBars <- lapply(names(rank.dict), function(rn) {
  tool.order <- bind_rows(default.results) %>%
    filter(rank_type == rn) %>% 
    ungroup() %>%
    filter(rank_cat == '5') %>%
    dplyr::select(tool, n, n_total) %>%
     unique() %>% 
    arrange(desc(n_total), desc(n))
  
  gg.defaultBar <- bind_rows(default.results)%>% 
    filter(rank_type == rn) %>%
    mutate(run_type = 'Default parameters',
           tool = factor(tool, levels = rev(tool.order$tool))) %>%
    ggplot(aes(x = tool,  y =  n, fill = rank_cat)) + 
    geom_bar(stat="identity", color="black") + theme_cowplot() +
    facet_wrap(~run_type, scales = 'free') +
    xlab('') + ylab("Count") + labs(fill=sprintf("Threshold\n(%s)", rn)) +
    scale_fill_manual(values = c(pal_igv("default")("51")[1:4], "gray46", "white"),
                      breaks=c('Labels recovered', '30', '10', '5', 
                                   'Processed datasets', 'NA')) +
    theme_cowplot(font_size = 7) +  ylim(0, 45) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 
  
  
  gg.jitter <- bind_rows(lapply(hitter.results, bind_rows)) %>%
    filter(rank_type == rn) %>%
    group_by(tool, var, rank_type) %>%
    summarise(n = sum(n), n_total = n_total) %>%
    mutate(run_type = 'Best parameters',
           tool = factor(tool, levels = rev(tool.order$tool))) %>%
    ggplot(aes(x = tool,  y =  n)) + geom_jitter(width = 0.15, alpha = 0.5, size = 0.75) +
    facet_wrap(~run_type, scales = 'free') +
    xlab('') + ylab("# of labels \n recovered (rank <= 30)") +
    labs(fill=sprintf("Threshold\n(%s)", rn)) +
    theme_cowplot(font_size = 7) + ylim(0, 45) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  
  
  
  gg.bestBar <- bind_rows(lapply(hitter.results, bind_rows)) %>%
    filter(rank_type == rn) %>%
    group_by(tool, rank_type) %>%
    filter(n_total == max(n_total)) %>%
    filter(var != 'nonorm') %>%
    filter(var %in% var[which(n[rank_cat == '30'] == min(n[rank_cat == '30']))])  %>%
    filter(var %in% var[which(n[rank_cat == '5'] == max(n[rank_cat == '5']))])  %>%
    ungroup() %>%
    dplyr::select(-var) %>% unique() %>%
    mutate(run_type = 'Best parameters',
           tool = factor(tool, levels = rev(tool.order$tool))) %>%
    ggplot(aes(x = tool,  y =  n, fill = rank_cat)) + 
    geom_bar(stat="identity", color="black") + theme_cowplot() + facet_wrap(~run_type, scales = 'free') +
    xlab('') + ylab("Count") + labs(fill=sprintf("Threshold\n(%s)", rn)) +
    scale_fill_manual(values = c(pal_igv("default")("51")[1:4], "gray46", "white"),
                      breaks=c('Labels recovered', '30', '10', '5', 
                                   'Processed datasets', 'NA')) +
    theme_cowplot(font_size = 7) + ylim(0, 45) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  
  return(list(gg.defaultBar, gg.jitter, gg.bestBar))
})
gg.recovBars <- do.call(c, gg.recovBars)

paper <- plot_grid(plotlist = c(gg.recovBars[1], gg.recovBars[4], gg.recovBars[2], gg.recovBars[5],
                                gg.recovBars[3], gg.recovBars[6]),
                   align = "hv", labels = c("A", "B", "C", "D", "E", "F"), axis = "tblr", 
                   nrow = 3, label_size = 10)

# Save plot
ggsave(paste0(fig.path, "Supp_fig_7.pdf"),
       paper, device = "pdf", width = 16, height = 16, units = "cm")



```


