---
title: "ChIP-seq TF tool result - Metric comparison"
author: "Leonor Schubert Santana"
date: "`r Sys.Date()`" 
site: workflowr::wflow_site
output:
   workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=F, message=F)
```

```{r data_preparation}
# Load libraries
library(tidyverse)
library(cowplot)
library(ggsci)

# Load utils.functions file
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/utils_functions.R")
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/read_functions.R")

# Define output path
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/'
chip.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/data/chipseq/'
fig.path <- "/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/paperPlots_revisions/"

# Find benchmark.rds 
benchmark.rds <- list.files(out.path, recursive = T, pattern = 'benchmark', full.names = T)
benchmark.rds <- benchmark.rds[-grep(benchmark.rds, pattern = 'atac|_bg')]
tools <- basename(benchmark.rds) %>% gsub('_.*', '', .) %>% unique()

# Define parameters
var.dict <- list('BART' = c('statistic' = T, 'pvalue' = F, 'zscore' = T,
                            'max_auc' = T, 're_rank' = F, 'irwin_hall_pvalue' = T),
                 'CRCmapper' = c('in_degree' = T,  'in_degree_norm' = T, 'out_degree' = T, 
                                 'out_degree_norm' = T, 'betweenness' = T, 'betweenness_norm' = T,
                                 'alpha_centrality' = T, 'eigenvector' = T,  'total_degree' = T,
                                 'total_degree_norm' = T),
                 'lola' = c('pValueLog' = T, 'oddsRatio' = T, 'support' = T,
                            'rnkPV' = F, 'rnkOR' = F, 'rnkSup' = F, 
                            'maxRnk' = F, 'meanRnk' = F),
                 'MEIRLOP' = c('coef' = T, 'auc' = T, 'pval' = F, 'padj' = F, 'percent_peaks' = T),
                 'TFEA' = c("E-Score" = T, "Corrected E-Score" = T, 'Events' = T, 
                            "P-adj" = F, "Corrected P-adj" = F))

# Define output path
overview.df <- read_rds('~/projects/tf_tool_benchmark/output/benchmark_data/chipseq/overview.RDS')
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/chipseq_metrics/'
rds.files <- list.files(out.path, full.names = T, recursive = T, pattern = 'RDS')
rds.files <- rds.files[grep(rds.files, pattern = 'benchmark.RDS')]


#out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/chipseq/'
#rds.files2 <- list.files(out.path, pattern = 'benchmark.RDS', full.names = T, recursive = T)
#tool <- 'lola'
#x <- read_rds(rds.files[grep(rds.files, pattern = tool)])
#y <- read_rds(rds.files2[grep(rds.files2, pattern = tool)])
#y[[1]] %>%
#  dplyr::select(1:3) %>%
#  dplyr::rename(rank_y = rank) %>%
#  left_join(., x$meanRnk) 
#  ggplot(aes(x =rank_y, y =rank)) + geom_point()

# Rank dict
rank.dict <- c('stringent' = 'rankStr', 'relaxed' = 'rankUnstr')
plot.list <- list()

for(rn in names(rank.dict)) {
  hitter.df <- lapply(rds.files, function(rds.file) {
    x <- read_rds(rds.file)  
    tool <- str_extract(rds.file, pattern = 'BART|CRCmapper|MEIRLOP|lola|TFEA')
    tool <- ifelse(tool == 'lola', 'LOLA', tool)
    lapply(names(x), function(var.name) {
      x[[var.name]] %>%
        as_tibble() %>%
        dplyr::rename('rankStr' = 'rank') %>%
        dplyr::rename('rank' = as.character(rank.dict[[rn]])) %>%
        mutate(tool = tool, var = var.name, rank = rank*possible_ranks) %>%
        group_by(tool, var) %>%
        mutate(rank_cat = case_when(rank <= 5 ~ '5',
                                        rank > 5 & rank <= 10 ~ '10',
                                        rank > 10 & rank <= 30 ~ '30',
                                        rank > 30 ~ 'Labels recovered',
                                        is.na(rank) ~ 'Processed datasets')) %>%
        group_by(tool, var, rank_cat) %>%
        summarise(n = n()) 
    }) %>% bind_rows
  }) %>% bind_rows
    
  # PLOT: Top X barplot
  gg.topHittesBar <- hitter.df %>% 
    #summarise(n = 84 - sum(n)) %>%
    #mutate(rank_cat = 'NA') %>%
    #dplyr::select(tool, var, rank_cat, n) %>%
    #bind_rows(., hitter.df) %>%
    mutate(rank_cat = factor(rank_cat, levels = rev(c( '5', '10', '30', 
                                                   'Labels recovered',
                                                   'Processed datasets', 'NA')))) %>%
    filter(rank_cat %in% c('5', '10', '30')) %>%
    group_by(var) %>%
    mutate(n_total = sum(n[rank_cat %in% c('5', '10', '30')])) %>%
    ungroup %>%
    mutate(var = factor(var, levels = unique(var[order(n_total)]))) %>%
    ggplot(aes(x = var,  y =  n, fill = rank_cat)) + facet_wrap(~tool, scales = 'free') +
    geom_bar(stat="identity", color="black") + theme_cowplot() + coord_flip() +
    #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    xlab("") + ylab("Count") + labs(fill=sprintf("Threshold\n(%s)", rn)) +
    scale_fill_manual(values = c(pal_igv("default")("51")[1:4], "gray46", "white"),
                      breaks=c('Labels recovered', '30', '10', '5', 
                               'Processed datasets', 'NA'))  
  plot.list[[rn]] <- gg.topHittesBar
  print(gg.topHittesBar)  
  cat('\n\n')
}

# Change font size
plot.list <- lapply(plot.list, function(p) {
  p + theme_cowplot(font_size = 7) 
        #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 
})

# Print plot
paper <- plot_grid(plotlist = plot.list, ncol=1, nrow=2,
                  align = "hv", labels = c("A", "B"), label_x = -0.02, axis = "tblr")

# Save plot
ggsave(paste0(fig.path, "Supp_fig_5_AB.pdf"),
       paper, device = "pdf", width = 18, height = 12, units = "cm")
```

```{r corr_analysis}
## Find output txts
#tool <- 'TFEA'
#out.txts <- list.files(chip.path, pattern = out.dict[tool], full.names = T,
#                       recursive = T)
#out.txts <- out.txts[!grepl(out.txts, pattern = '(neutral|rmd)_bg')]
#out.txts <- out.txts[grep(out.txts, pattern = tool, ignore.case = T)]
#x <- read_tsv(out.txts[1])
#
#vcor.df <- lapply(out.txts, function(txt) {
#  print(txt)
#  cor(read_tsv(txt)[,names(var.dict[[tool]])]) %>%
#    reshape2::melt(.) %>% 
#    mutate(sample = unlist(str_split(txt, pattern = '/'))[11],
#           label = unlist(str_split(txt, pattern = '/'))[16],
#           tool = tool)
#}) 
#
#
#default.metric <- as.character(names(var.dict[[tool]]))[1]
#
#vcor.df <- vcor.df %>%
#  bind_rows %>% 
#  dplyr::filter(Var1 == default.metric &
#                Var2 != default.metric) %>%
#  group_by(Var2) %>%
#  summarise(value = default.metric)
#  
#
#mean(bind_rows(vcor.df)$value, na.rm=T) 
#  ggplot(aes(x = reorder(Var2, value), y = value)) + geom_boxplot()


```


