---
title: "ChIP-seq TF tool - Background comparison"
author: "Leonor Schubert Santana"
date: "`r Sys.Date()`" 
site: workflowr::wflow_site
output:
   workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=F, message=F)
```

```{r data_preparation}
# Load libraries
library(tidyverse)
library(cowplot)
library(ggsci)

# Load utils.functions file
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/utils_functions.R")
source("/da/dmp/cb/steinse5/projects/tf_tool_benchmark/code/R/read_functions.R")

# Define output path
out.path <- '/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/benchmark_data/'

# Find benchmark.rds 
tools <- c('homer')
benchmark.rds <- list.files(out.path, recursive = T, pattern = 'benchmark', full.names = T)
benchmark.rds <- benchmark.rds[-grep(benchmark.rds, pattern = 'atac')]
benchmark.rds <- benchmark.rds[grep(benchmark.rds, pattern = paste(tools, collapse = '|'))]
```

## TF label rank comparison {.tabset}

```{r comparison_tf_rank, results='asis'}
# Read rankings 
ranks.df <- lapply(benchmark.rds[grep(benchmark.rds, pattern = 'homer')], function(rds) {
  print(rds)
  ranks.df <- read_rds(rds)
  lapply(names(ranks.df), function(type.name) {
    read_rds(rds)[[type.name]][,1:3]  %>%
        mutate(tool = 'homer', #tool,
               type = type.name,
               bg = str_extract(rds, pattern = '(rmd|neutral)_bg'), 
               bg = ifelse(is.na(bg), 'diff_bg', bg),
               tool_label = sprintf('%s_%s', tool, bg)) %>% 
      dplyr::select(-tool, -bg)
  }) %>% bind_rows
}) %>% bind_rows() 
 
# Prepare for plotting  
ranks.df <- ranks.df %>%
  mutate(tool_label = if_else(grepl(type, pattern = 'no backgr'), 'homer_shuffle_bg', tool_label),
         type = if_else(grepl(type, pattern = 'lambert'), 'lambert', 'default'))

  
ranks.df %>% 
  mutate(tool_label = gsub('homer_', '', tool_label), tool = 'homer') %>%
  ggplot(aes(x = reorder(tool_label, rank), y = rank, fill = type)) +
  geom_boxplot() + ylab('Rank') + xlab('') +  facet_wrap(~tool) +
  scale_fill_manual(values = c('grey', 'darkred'), name = 'Motif lib') +
  theme_cowplot() 

ranks.mat <- ranks.df %>% 
  mutate(tool_label = paste(tool_label, type, sep = '_'),
         label = paste(study, label, sep = '_')) %>%
  ungroup() %>%
  dplyr::select(label, tool_label, rank) %>%
  spread(tool_label, rank, fill = 1) %>%
  column_to_rownames('label')

library(ComplexHeatmap) 
col.fun <- circlize::colorRamp2(c(0, 1), c("white", "red")) 
top.anno <- tibble(params = colnames(ranks.mat)) %>% 
  mutate(lib = gsub('.*_', '', params),
         lib = str_to_title(lib),
         bg = gsub('homer_|_(lambert|default)', '', params),
         bg = str_to_title(gsub('_bg', '', bg)),
         bg = ifelse(bg == 'Shuffle', 'Default', bg)) %>%
  dplyr::rename('Motif lib' = lib, 'Background' = bg) %>%
  column_to_rownames('params') %>%
  as.data.frame()
top.anno <- HeatmapAnnotation(df = top.anno, 
                              col = list('Motif lib' = c('Default' = 'lightgrey', 'Lambert' ='darkred'),
                                         'Background' = c('Diff' = '#ff7f00', 'Neutral' = '#33a02c',
                                                  'Rmd' = '#1f78b4', 'Default' = 'darkgrey')))
cheat <- Heatmap(cor(ranks.mat), name = 'HOMER\nrank cor', col = col.fun,
        top_annotation = top.anno, show_column_names = F, show_row_names = F)
print(cheat)

fig.path <- "/da/dmp/cb/steinse5/projects/tf_tool_benchmark/output/paperPlots_revisions/"
pdf(file=paste0(fig.path, "Supp_fig_5_C.pdf"), width = 5, height = 3.5)
draw(cheat) #, annotation_legend_list = anno.legend)
dev.off()
  
```
 
## Hitter barplot {.tabset}

```{r hitter_bar, results='asis'}
# Iterate over tools and read ATAC-seq TF ranks
ranks.df <- lapply(benchmark.rds[grep(benchmark.rds, pattern = 'homer')], function(rds) {
  print(rds)
  ranks.df <- read_rds(rds)
  lapply(names(ranks.df), function(type.name) {
    read_rds(rds)[[type.name]]  %>%
        mutate(tool = 'homer', #tool,
               type = type.name,
               bg = str_extract(rds, pattern = '(rmd|neutral)_bg'), 
               bg = ifelse(is.na(bg), 'diff_bg', bg),
               tool_label = sprintf('%s_%s', tool, bg)) %>% 
      dplyr::select(-tool, -bg)
  }) %>% bind_rows
}) %>% bind_rows() %>% dplyr::rename(rankStr = rank) 

# Prepare for plotting  
ranks.df <- ranks.df %>%
  mutate(tool_label = if_else(grepl(type, pattern = 'no backgr'), 'homer_shuffle_bg', tool_label),
         type = if_else(grepl(type, pattern = 'lambert'), 'lambert', 'default'),
         tool_label = paste(tool_label, type, sep = '_'),
         tool_label = gsub('homer_', '', tool_label))


# Rank dict
rank.dict <- c('stringent' = 'rankStr', 'relaxed' = 'rankUnstr')

for(rn in names(rank.dict)) {
 # Compute number of hitters 
  hitter.df <- ranks.df %>% 
    dplyr::rename(rank = as.character(rank.dict[rn])) %>%
    group_by(tool_label) %>%
    mutate(rank = 1+(possible_ranks*rank), 
           rank_cat = case_when(rank <= 5 ~ '5',
                                    rank > 5 & rank <= 10 ~ '10',
                                    rank > 10 & rank <= 30 ~ '30',
                                    rank > 30 ~ 'Labels recovered',
                                    is.na(rank) ~ 'Processed datasets')) %>%
    group_by(tool_label, rank_cat) %>%
    summarise(n = n()) 
  
  # SORT tools for plotting
  tools.sorted <- hitter.df %>%
    filter(rank_cat %in% c('5', '10', '30')) %>%
    summarise(n = sum(n)) %>%
    arrange(desc(n)) 
  tools.sorted <- 
    hitter.df %>% filter(!(tool_label %in% tools.sorted$tool_label)) %>% 
    summarise(n = sum(n)) %>% 
    bind_rows(tools.sorted, .)
  
  # PLOT: Top X barplot
  gg.topHittesBar <- hitter.df %>% 
    summarise(n = 84 - sum(n)) %>%
    mutate(rank_cat = 'NA') %>%
    dplyr::select(tool_label, rank_cat, n) %>%
    bind_rows(., hitter.df) %>%
    mutate(rank_cat = factor(rank_cat, levels = rev(c( '5', '10', '30', 
                                                   'Labels recovered',
                                                   'Processed datasets', 'NA'))),
           tool_label = factor(tool_label, levels = tools.sorted$tool_label)) %>%
    ggplot(aes(x = tool_label, y =  n, fill = rank_cat)) +
    geom_bar(stat="identity", color="black") + theme_cowplot() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    xlab("Method") + ylab("Count") + labs(fill=sprintf("Threshold (%s)", rn)) +
    scale_fill_manual(values = c(pal_igv("default")("51")[1:4], "gray46", "white"),
                      breaks=c('Labels recovered', '30', '10', '5', 
                               'Processed datasets', 'NA'))  
  print(gg.topHittesBar)
  cat('\n\n\n')
}
```
  
  
  
